Cloud testapp
Otus-DevOps-2020-02/reuvengi_infra pull request #3
Opened 2020-03-21 07:00 UTC by reuvengi

# Выполнено ДЗ №6

 - [ x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1. Были созданы скрипты

  install_mongodb.sh
  install_ruby.sh
  deploy.sh

2. Эти скрипты были объеденены в  startup-script.sh

3. Команда gcloud  со startup-script

4. Создание правила firewall через gcloud

## Как запустить проект:
 
gcloud compute instances create reddit-app --boot-disk-size=10GB --image-family ubuntu-1604-lts --image-project=ubuntu-os-cloud --machine-type=g1-small --tags puma-server --restart-on-failure  --metadata-from-file startup-script=startup-script.sh

## Как проверить работоспособность:
 - перейти по ссылке http://35.241.173.135:9292/

## PR checklist
 - [ x] Выставил label с номером домашнего задания
 - [ x] Выставил label с темой домашнего задания

2020-03-21 10:07 UTC, mrgreyves requested changes
Здравствуйте!) У вас проблемы со скриптами установки. По этому тесты и валятся. Возвращаю на доработку =(

2020-03-23 08:33 UTC, reuvengi commented
пофиксил

2020-03-23 18:22 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-03-25 15:42 UTC, achehonte commented
Добрый день, почему-то не доступна кнопка смержить

2020-03-26 17:18 UTC, merged